### ISSUE TITLE
Finalize meeting location with the client. 

### ISSUE THREAD

**Issue by mkuelker** [speaking-portal-project-team-a/The-Speaking-Portal-Project#11]
# Finalize meeting location with the client. 

## Possible rooms: 

- Sci 331 
- EME 1252
- ART 276
- SCI 253
- Prof's personal rooms in Flipke
- Fipke 301 
- Room in front of 301

**Comment by vnajack** [comment]
I booked EME 1252 which can fit 10 people (will need to find extra chairs) as a backup

Start time | 16:00 - Friday 23 September 2022
Duration | 90 minutes
End time | 17:30 - Friday 23 September 2022
Room | EME: Tower 2 - EME 1252

**Comment by LoganParker** [comment]
The meeting date & location was finalized as of last Thursday. Meetings going forward will occur online via discord
