### ISSUE TITLE
Add research template repo 

### ISSUE THREAD

**Issue by edouarde1** [speaking-portal-project-team-a/The-Speaking-Portal-Project#15]
**Describe what needs to get done**
Need to organize a place to put research notes. 

**Describe the solution you'd like**
Create a home directory 'research' and place docs into the directory. Outline a research template for us to place links and other research items

**Comment by mkuelker** [comment]
[This has been done.](https://github.com/speaking-portal-project-team-a/The-Speaking-Portal-Project/tree/team_research_notes)

I am closing this issue. Feel free to reopen if that is not the case.
