### ISSUE TITLE
UML diagram first draft 

### ISSUE THREAD

**Issue by edouarde1** [speaking-portal-project-team-a/The-Speaking-Portal-Project#18]
**Describe what needs to get done**
A surface level view of the system as a UML diagram. This diagram should be constructed in LucidChart or in Diagrams.net. 
 
The first draft of the UML digram should include the user, Kukararella web application, the animation add-on, and the interactions between each of these components.

**Describe the solution you'd like**
The final UML diagram should include input/output's between components (e.g API requests). The diagram should be organized. Keep in mind that this UML diagram will be more generalized as this is a first draft. 

**Additional context**

**Comment by LoganParker** [comment]
https://lucid.app/lucidchart/a3029471-c5d8-4cca-bd06-edf8966daa88/edit?viewport_loc=140%2C250%2C1675%2C968%2C0_0&invitationId=inv_866df4dc-c113-48da-a029-bbf4af03155e

**Comment by mkuelker** [comment]
[UML Relationships](https://lucid.app/lucidchart/343838c8-a8dc-4fb2-ab02-22b8cb0e6cb5/edit?viewport_loc=-10%2C-10%2C1696%2C817%2C0_0&invitationId=inv_58b51c62-9f5f-4b98-9b2a-df0f47df1283#)
