### ISSUE TITLE
High-level project description with correct identification of user groups

### ISSUE THREAD

**Issue by edouarde1** [speaking-portal-project-team-a/The-Speaking-Portal-Project#20]
**Describe what needs to get done**
Explain how each user group is expected to use the software differently. (Recall that in order for two users to be considered as being in two different user groups, they must use the system differently either via a functional or non-functional system requirement.)

**Describe the solution you'd like**

This section **must** be included in finalized PDF report.

**Comment by vnajack** [comment]
This deliverable is for section 1 of the Requirement Report Works (PDF) due Oct 21 by 11:59p.m.
