### ISSUE TITLE
Feasibility Report for Client

### ISSUE THREAD

**Issue by vnajack** [speaking-portal-project-team-a/The-Speaking-Portal-Project#34]
**Is this related to a problem? Please describe.**
For the next client meeting, the client requested that we research what's feasible, so this is for our presentation.

**Describe the solution you'd like**
- Markdown file to summarize team research into a feasibility report
- Maybe a PowerPoint to present to the client?

**What aspects are unclear - what needs to be done, or how it should be accomplished?**
- all team members research #26 
- the research should be compiled into the feasibility report
- a short presentation should explain where we see problems and our suggested approaches

**Additional context**
- this is not a deliverable for the course, but the client requested this for the next meeting (October 7, 2022)

**Comment by LoganParker** [comment]
This issue was closed post-merge of #26
