### ISSUE TITLE
Complile List of Items Needed from Client 

### ISSUE THREAD

**Issue by mkuelker** [speaking-portal-project-team-a/The-Speaking-Portal-Project#58]
**Describe what needs to get done**
We need to send our client a list of all the action items that need to be dealt with. This includes 
 - #56 
 - #38 
 - #37 

**Describe the solution you'd like**
Have these all items all assembled in a word doc before copy-pasting as a comment to the discord of questions

**Comment by LoganParker** [comment]
Is this issue still active? Have we sorted out our list of needs or will that be finalized next team meeting? @mkuelker

**Comment by mkuelker** [comment]
I think we can close this @LoganParker
