### ISSUE TITLE
Deliverable #1 - Program receives the avatar image, audio, text, and language from the local machine

### ISSUE THREAD

**Issue by LoganParker** [speaking-portal-project-team-a/The-Speaking-Portal-Project#62]
**Is this related to a problem? Please describe.**
Our program does not yet take in any inputs. 

**Describe the solution you'd like**
#59 must be completed in order to understand further how we will be receiving inputs. Then, additional issues must be created for implementation of input reception

**Describe the feature**
We need to retrieve audio, text, a selected language, and specified avatar from a user.

**What aspects are unclear - what needs to be done, or how it should be accomplished?**
We do not yet know how we are structuring our codebase - whether we are initially developing as an API or working towards translating the code into an API further down the line.

**Additional context**
Issue should be updated as further development occurs.

**Comment by LoganParker** [comment]
@mkuelker @vnajack @edouarde1, it appears deliverable 1 has been completed. Can we close this issue?

**Comment by LoganParker** [comment]
As this is taking input from a local machine, #59 is not relevant for this issue. We are currently retrieving inputs from the filesystem, and #59 will be required for the Peer Testing 2 Milestone.

**Comment by mkuelker** [comment]
This looks agreeable. Thanks for closing this!
